### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [jumpkick/graphviz-preview#11]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.3.0`) of this package:

1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: ```json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] } ```
1. Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `<pack-name>` package
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. Call ::getActiveTextEditor instead
1. Call Workspace::addOpener instead
1. Requiring `$` from `atom` is no longer supported. If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead: `{$} = require 'atom-space-pen-views'` or `$ = require 'jquery'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies. Or add `"jquery": "^2"` to your package dependencies.
1. Requiring `$$$` from `atom` is no longer supported. Please require `atom-space-pen-views` instead: `{$$$} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
1. Requiring `ScrollView` from `atom` is no longer supported. Please require `ScrollView` from `atom-space-pen-view` instead: `{ScrollView} = require 'atom-space-pen-views'` Note that the API has changed slightly! Please read the docs at https://github.com/atom/atom-space-pen-views Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
1. Use ::paneForURI instead.
1. If you would like your pane item with class `<ClassName>` to support modified behavior, please implement a `::onDidChangeModified()` method. If not, ignore this message. `::on` methods for items are no longer supported.
1. If you would like your pane item with class `<ClassName>` to support title change behavior, please implement a `::onDidChangeTitle()` method. `::on` methods for items are no longer supported. If not, ignore this message.
1. Pane item with class `<ClassName>` should implement `::getURI` instead of `::getUri`.
1. Use TextBuffer::onDidStopChanging instead. If you need the modified status, call TextBuffer::isModified yourself in your callback.
1. Use TextEditor::onDidChangePath instead
1. Use Workspace::getTextEditors instead
1. Use `::itemForURI` instead.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by wysiib** [comment]
I could provide a pull request fixing the deprecations. Is this project abandoned or still maintained?

**Comment by jumpkick** [comment]
I would be happy to accept it and publish a fix crediting you.

**Comment by wysiib** [comment]
Sounds good, i will look into it tomorrow!

**Comment by wysiib** [comment]
See pull request 2. Should fix all issues regarding deprecated api usage.

**Comment by jumpkick** [comment]
@wysiib thanks for your patch.  

I'm not sure if there's something wonky with my set-up, but I get an exception in pane.js, line 774.   Even with the exception it does render, so I'll release it the way it is (because graphviz-preview is totally broken on 1.0.x) and dump my stack into another ticket.

**Comment by wysiib** [comment]
I did not see an exception on my side. What did you do to make it occur? And how did you observe it? I will try to reproduce and see if it is caused by the patch.

**Comment by bendisposto** [comment]
I get the same exception:
- Open .dot file
- Show preview (works)
- Keep the preview open, change the dot file and save (error, but the preview is updated correctly)

**Comment by jumpkick** [comment]
@wysiib Here's the bug report atom generated #13, I'm going to finish updating all the other stuff that'd deprecated in my atom env and restart to see if I can reproduce it.

**Comment by wysiib** [comment]
See pull request #14

**Comment by jumpkick** [comment]
I believe all of the issues are now addressed, I released v1.0.0 with one other minor change to get rid of a JQuery::Trigger complaint from DepCop.    Cheers and thanks for all of your help @wysiib, I would not have been able to tackle the mountain of API changes on my own.   Also thanks to @bendisposto for testing.

**Comment by wysiib** [comment]
You're welcome!
