### ISSUE TITLE
Preview not rendering "refuse to frame ... because it violates the following Content Security Policy directive: "default-src *""

### ISSUE THREAD

**Issue by e0725675** [jumpkick/graphviz-preview#25]
Hello,
whenever I try to preview a dot file the page stays white and I get the following exception in the dev console:
C:\Users\<username_anonymized>\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:5221

Refused to frame 'data:text/html;charset=utf-8,%3C!doctype%20html%3E%0A%3Chtml%3E%0A%20%20%3C…%22visibility:%20hidden;%22%3E%3C/div%3E%0A%20%20%3C/body%3E%0A%3C/html%3E' 
because it violates the following Content Security Policy directive: "default-src *".
Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
(anonymous function) 		@ C:\Users\<username_anonymized>\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:5221
jQuery.fn.extend.domManip 		@ C:\Users\<username_anonymized>\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:5414
jQuery.fn.extend.append 		@ C:\Users\<username_anonymized>\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:5218
(anonymous function) 		@ C:\Users\<username_anonymized>\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:5333
jQuery.access 		@ C:\Users\<username_anonymized>\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:3491
jQuery.fn.extend.html 		@ C:\Users\<username_anonymized>\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\jquery\dist\jquery.js:5300
module.exports.GraphvizPreviewView.renderHTMLCode 		@ graphviz-preview-view.coffee:239
module.exports.GraphvizPreviewView.renderHTML 		@ graphviz-preview-view.coffee:85
(anonymous function) 		@ graphviz-preview.coffee:46
_tickCallback 		@ node.js:392

So far i have disabled all my packages to make sure it's not some incompatibility issue, but it did not help. It fails on any .dot file.

edit: I am not sure how to reproduce the issue since it simply happens to all .dot files I try to preview.
edit2: But it has worked just fine before. I had just updated atom when it broke.

**Comment by stoneburner** [comment]
same problem here

**Comment by e0725675** [comment]
Just realized this is most likely a duplicate of #20 
I will cross-reference it.

**Comment by luckyjazzbo** [comment]
+1

**Comment by 0cd** [comment]
+1

**Comment by deftdawg** [comment]
Presumably 1.7.0 fixed this issue, if not scream and I'll reopen it.
