### ISSUE TITLE
Nothing appear after I upgraded into atom 1.7.2

### ISSUE THREAD

**Issue by maplewizard** [jumpkick/graphviz-preview#26]
I used to use graphviz-preview and it works fine. But after I upgrade my atom into 1.7.2. It fail to render anything. Now, nothing appear. How can I solve this?

**Comment by khalilgharbaoui** [comment]
Same here... but i've installed graphviz and open-in-browser 

I just open the .dot file in atom and do CTRL+OPTION+Q and it opens by default in graphviz app.

Temporary solution... Not ideal but working!

https://atom.io/packages/open-in-browser 
http://www.graphviz.org/Download..php

**Comment by corporatepiyush** [comment]
same here too. There aren't any errors. it fails silently !

**Comment by dalonng** [comment]
same here to

**Comment by selimober** [comment]
Here is the error it logs to console
```
Refused to frame 'data:text/html;charset=utf-8,<!doctype html>
<html>
  <…"visibility: hidden;"></div>
  </body>
</html>' because it violates the following Content Security Policy directive: "default-src *". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by jakubczaplicki** [comment]
Atom 1.7.3 + latest plugin version: the preview shows a white blank page (no graph) despite correct graph code.

**Comment by stefanopassador** [comment]
Same here. Hope it will be fixed soon

**Comment by deftdawg** [comment]
Try updating the plugin to 1.7.0 ... let me know if it works doesn't work.

**Comment by stefanopassador** [comment]
For me works! Thank you!
