### ISSUE TITLE
Fit preview size to window

### ISSUE THREAD

**Issue by nlehuen** [jumpkick/graphviz-preview#3]
Hi,

That would be awesome if the preview view was scaled down to fit the available space. I'm editing a big graph, and unfortunately the part I'm editing is not directly visible, so I have to scroll to see my changes.

Great package, otherwise !

**Comment by jumpkick** [comment]
Please feel free to hack at the offset formula and patch/pull request, I spent way too much time on it and it's still not perfect. :\
