### ISSUE TITLE
"Dot syntax error" on valid DOT file

### ISSUE THREAD

**Issue by erkaun** [jumpkick/graphviz-preview#31]
I'm new to Atom, and really like the plugin, but have an issue with `graphviz-preview 1.7.0`. Some graphs, which are valid when I use the `dot` command line (I'm using the version shown below), produce a red "Dot syntax error" message. 

I'm going to attach a graph that produces the problem, once I reduce it to a minimal version. There's no single line that seems to produce the problem, but it seems to happen when I'm using subgraphs (some of them anyway).

Is there a way to configure the plugin to use my local `dot` install?

My `dot` version info:

``````
dot - graphviz version 2.36.0 (20140111.2315)`
libdir = "/usr/local/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.6.dylib
Using render: dot:core
Using device: dot:dot:core```
``````

**Comment by erkaun** [comment]
Here's an example:

```
digraph example {
    "Search" -> "new API" [label="query"];
    "Tool" -> "Analysis";

    "new API" -> "Retrieve" [label="query"];
    "Retrieve" -> "new API" [label="ranked\nresults"];

    subgraph cluster_r_r {label="R&R";
      {rank=same; "Retrieve"; "Rank";}
      "Retrieve" -> "Rank" [label="feature\nvectors"];
      "Rank" -> "Retrieve" [label="ranked\ndocuments"];
      "Retrieve" -> "Solr" [label="query"];
    }

    "new API" -> "Logging" [label="click"];
    "Retrieve" -> "Logging";
    "Logging Service" -> "other";
}
```

If I change the last line to remove the word `Service` from the node, or change the first line to remove `new` to make the node just `API`, the diagram renders. I'd just like to know what the problem is. Thanks!

**Comment by deftdawg** [comment]
1) graphviz-preview is based on viz.js a JavaScript implementation of dot
rendering, it has no connection to the underlying OS version (it wouldn't
be portable if it did)

2) sounds like viz.js doesn't like your node names (could be the spaces),
it seems a bit painful to spell them out every time anyway, have you
thought of making short node names with labels.

Take a look at the "atom" node on the plugin example to see what I mean by
that.
https://raw.githubusercontent.com/jumpkick/graphviz-preview/master/assets/graphviz-preview-screenshot.png

Anyway, if that doesn't work, I'm not going to attempt to fix viz.js.

**Comment by erkaun** [comment]
Completely reasonable - I'll shorten the names and give that a go. I wasn't aware of `viz.js` but if I have any additional issues that warrant an issue, I'll report it there.

Thanks for the quick feedback.
