### ISSUE TITLE
Graphviz-preview install hangs when apm install reaches "atom-space-pen-views@2.0.5"

### ISSUE THREAD

**Issue by despairblue** [jumpkick/graphviz-preview#7]
Issuing an `apm install graphviz-preview` outputs: 
```
Installing graphviz-preview to /home/despairblue/.atom/packages
```
and then apm just keeps using 100% cpu and takung up memory until it's killed.

Cloning the repo and issuing `npm install` works fine.

@jumpkick can this be reproduced on your end?

**Comment by jackmaney** [comment]
I'm getting the same error on OSX 10.9.5. Lemme try installing manually...

**Comment by jumpkick** [comment]
@despairblue @jackmaney I observe a similar problem both using preference pane to install and using apm from the command line.   When I run `apm install --verbose graphviz-preview`, it ticks along until it hits this

    ...
    REQUEST end event https://registry.npmjs.org/mkdirp
    REQUEST emitting complete https://registry.npmjs.org/mkdirp
    graphviz-preview@1.0.0 node_modules/graphviz-preview
    └── atom-space-pen-views@2.0.5 (fuzzaldrin@2.1.0, space-pen@5.1.1)

At which point you have to kill it, but graphviz-preview is already installed and should work fine when you start up Atom again.

**Comment by deftdawg** [comment]
Try with graphviz-plugin 1.7.0, let me know if this still occurs

**Comment by deftdawg** [comment]
Since I haven't heard any screaming that this is still broken, I'm going to assume 1.7.0 fixed this issue.
